#!/bin/bash

ALIAS_FILE=/home/mitch/git/goto/aliases.txt

usage='Usage: goto [-m destination] name'

if [[ $# == 0 ]] ; then
  echo "$usage"
  return 1
fi

# getopt seemed like overkill
if [[ $1 == '-m' ]] ; then
  abspath=$(cd $(dirname $2); pwd)/$(basename $2)

  if ! [[ -e $abspath ]] ; then
    echo "No such directory: $abspath"
    return 2
  fi

  existing_re="^$abspath |$3$"
  _=`grep -E "$existing_re" $ALIAS_FILE`
  # If the alias is already there
  if [[ $? == 0 ]] ; then
    tmpfile=/tmp/goto.tmp
    touch "$tmpfile"
    grep -v -E "$existing_re" $ALIAS_FILE > tmpfile
    mv $tmpfile $ALIAS_FILE
  fi

  echo "$abspath $3" >> $ALIAS_FILE
else
  re="$1$"
  newdir=`cat $ALIAS_FILE | grep -e $re | awk '{print $1}'`
  if [[ -e $newdir ]] ; then
    cd $newdir
    return 0
  else
    echo "No alias for '$1'."
    return -1
  fi
fi
